# Generated by Django 2.2.3 on 2019-07-18 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190718_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='BifUserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('social media', 'social'), ('note', 'note'), ('feedback', 'feedback')], max_length=12)),
                ('action_payload', models.TextField()),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_action', to='users.BifCoinUser')),
            ],
        ),
    ]
