# Generated by Django 2.2.3 on 2019-07-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190721_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='bifcoinuser',
            name='pending_balance',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
