# Generated by Django 2.2.3 on 2019-07-18 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_auto_20190716_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkStateLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_network_update', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='BifTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pending', models.BooleanField()),
                ('mined', models.BooleanField()),
                ('recipient', models.ManyToManyField(related_name='transactions_received', to='users.BifCoinUser')),
                ('sender', models.ManyToManyField(related_name='transactions_sent', to='users.BifCoinUser')),
            ],
        ),
    ]
