# Generated by Django 2.2.3 on 2019-07-18 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190718_0559'),
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biftransaction',
            name='mined',
        ),
        migrations.AddField(
            model_name='networkstatelog',
            name='mining_reward',
            field=models.IntegerField(default=10),
        ),
        migrations.CreateModel(
            name='MinedTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pending', models.BooleanField()),
                ('proposal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.ClaimedProposal')),
                ('recipient', models.ManyToManyField(related_name='transactions_mined', to='users.BifCoinUser')),
            ],
        ),
    ]
