# Generated by Django 2.2.3 on 2019-07-18 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190718_0559'),
        ('blockchain', '0002_auto_20190718_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biftransaction',
            name='recipient',
        ),
        migrations.AddField(
            model_name='biftransaction',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_received', to='users.BifCoinUser'),
        ),
        migrations.RemoveField(
            model_name='biftransaction',
            name='sender',
        ),
        migrations.AddField(
            model_name='biftransaction',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_sent', to='users.BifCoinUser'),
        ),
        migrations.AlterField(
            model_name='minedtransaction',
            name='proposal',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.ClaimedProposal'),
        ),
        migrations.RemoveField(
            model_name='minedtransaction',
            name='recipient',
        ),
        migrations.AddField(
            model_name='minedtransaction',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_mined', to='users.BifCoinUser'),
        ),
    ]
