# Generated by Django 2.2.3 on 2019-07-18 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_bifuseraction'),
        ('blockchain', '0003_auto_20190718_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkstatelog',
            name='feedback_reward',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='networkstatelog',
            name='note_reward',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='networkstatelog',
            name='social_reward',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='minedtransaction',
            name='proposal',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.ClaimedProposal'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EarnedTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('pending', models.BooleanField()),
                ('action', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.BifUserAction')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_earned', to='users.BifCoinUser')),
            ],
        ),
    ]
