# Generated by Django 2.2.3 on 2019-07-22 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0006_auto_20190721_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minedtransaction',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mined_transaction', to='users.ClaimedProposal'),
        ),
        migrations.AlterField(
            model_name='minedtransaction',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.BifCoinUser'),
        ),
    ]
