# Generated by Django 2.2.3 on 2019-07-22 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0007_auto_20190722_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkstatelog',
            name='installation_mining_reward',
            field=models.IntegerField(default=1),
        ),
    ]
