# Generated by Django 2.2.3 on 2019-07-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0008_networkstatelog_installation_mining_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkstatelog',
            name='approved_transactions',
            field=models.IntegerField(default=0),
        ),
    ]
