# Generated by Django 2.2.3 on 2019-07-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0009_auto_20190722_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkstatelog',
            name='last_network_update',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='networkstatelog',
            name='mining_reward',
            field=models.IntegerField(default=11),
        ),
    ]
